# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Delivery-timer-order-timeline"
client_id = "62de78c7cc6d1b1ee9901e2c585e0169"
application_url = "https://genealogy-behaviour-letting-vinyl.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://genealogy-behaviour-letting-vinyl.trycloudflare.com/auth/callback",
  "https://genealogy-behaviour-letting-vinyl.trycloudflare.com/auth/shopify/callback",
  "https://genealogy-behaviour-letting-vinyl.trycloudflare.com/api/auth/callback",
  "https://genealogy-behaviour-letting-vinyl.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "grocery-shop-23.myshopify.com"
